IPMI/Controllers/IpmiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IPMI.Entity;
using IPMI.Repository;
using IPMI.Services;
using IPMI.Models;
using IPMI.Models.Repo;
using System.IO;
using System.Configuration;
using System.Data.SqlClient;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Data;

namespace IPMI.Controllers
{
    public class IpmiController : Controller
    {
        private IMService objIpmi;
        private DeptService objDept;
        private AnalisaService ObjAnalisa;
        public IpmiController()
        {
            this.objIpmi = new IMService();
            this.objDept = new DeptService();
            this.ObjAnalisa = new AnalisaService();
        }
        // GET: Ipmi
        public ActionResult Index()
        {
            object[] nama = { User.Identity.Name };
            string NamaDept = objDept.GetDeptByID(nama);
            ViewBag.Dari = NamaDept;
            object[] dept = { NamaDept };
            var result = objIpmi.GetAll(dept);
            
            return View(result);
        }

        // GET: Ipmi/Details/5
        public ActionResult Details(string id)
        {
            ViewBag.IdDept = GetDeptToList();
            object[] parameters = { id };
            ViewData["ListIpmi"] = objIpmi.GetbyID(parameters);
            return View();
        }

        // GET: Ipmi/Create
        public ActionResult Create()
        {
            ViewData["Customer"] = CustomerToList();
            ViewBag.IdDept = GetDeptToList();
            object[] nama = { User.Identity.Name };
            string NamaDept = objDept.GetDeptByID(nama);
            ViewBag.Dari = NamaDept;
            object[] dept = { NamaDept };
            ViewBag.AutoNO = objIpmi.AutoNo(dept);

            return View();
        }

        // POST: Ipmi/Create
        [HttpPost]
        public ActionResult Create(tIpmi model)
        {
            int result = 0;

            model.CreatedBy = User.Identity.Name;
            object[] parameters = { model.NoIPMI, model.Tgl, model.CustomerId.TrimEnd(), model.CustomerName.TrimEnd()
                                        ,model.Dari, model.ke
                                        ,model.Masalah, model.Jumlah
                                        ,model.FileName
                                        ,model.CreatedBy, model.FileName1};
            result = objIpmi.Insert(parameters);
            if (result == 1)
            {
                string email = string.Empty;
                email = objIpmi.GetEmail(model.ke);

                //MailMessage mail = new MailMessage("ipmi@tsmu.co.id", email);
                MailMessage mail = new MailMessage();
                mail.IsBodyHtml = true;
                mail.From = new MailAddress("ipmi@tsmu.co.id", "IPMI");
                mail.To.Add(new MailAddress(email));
                var smpt = new SmtpClient
                {
                    Host = "mail.tsmu.co.id",
                    Port = 25,
                    EnableSsl = false,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    Credentials = new NetworkCredential("ipmi@tsmu.co.id", "svPyyO(++6cj"),
                    Timeout = 20000
                };
                //var body = new StringBuilder();
                //body.AppendFormat("Ada Masalah baru :");
                //body.AppendLine(@">Dari =" + model.Dari);
                //body.AppendLine(@">Masalah =" + model.Masalah);
                //body.AppendLine("<a href='https://srv02.tsmu.co.id/ipmi/Account/Login?ReturnUrl=%2Fipmi%2F'>Klik di sini untuk Login</a>");
                //mail.Body = body.ToString();
                string emailSubject = "IPMI Notification " + model.NoIPMI;
                mail.Subject = emailSubject;
                mail.Body = "Identifikasi Masalah baru : <br /> > Dari =" + model.Dari + "<br /> > Msalah = " + model.Masalah + "<br /> <a href='https://srv02.tsmu.co.id/ipmi/Account/Login?ReturnUrl=%2Fipmi%2F'>Klik di sini untuk Login</a>";
                mail.IsBodyHtml = true;
                mail.CC.Add("log@tsmu.co.id");
                smpt.Send(mail);
                this.AddToastMessage("IPMI", "Data berhasil di simpan !", ToastType.Success);
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                this.AddToastMessage("IPMI", "Data Tidak Berhasil di simpan !", ToastType.Error);
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }

        }

        // GET: Ipmi/Edit/5
        public ActionResult Edit(string id)
        {
            ViewData["Customer"] = CustomerToList();
            ViewBag.IdDept = GetDeptToList();
            object[] parameters = { id };
            ViewData["ListIpmi"] = objIpmi.GetbyID(parameters);
            return View();
        }

        // POST: Ipmi/Edit/5
        [HttpPost]
        public ActionResult Edit(tIpmi models)
        {
            int result = 0;

            try
            {
                models.UpdatedBy = User.Identity.Name;
                object[] parameters = { models.NoIPMI, models.Tgl, models.CustomerId.TrimEnd(), models.CustomerName.TrimEnd()
                                        ,models.Dari, models.ke
                                        ,models.Masalah, models.Jumlah
                                        ,models.FileName
                                        ,models.UpdatedBy, models.FileName1};
                result = objIpmi.Update(parameters);
                if (result == 1)
                {

                    this.AddToastMessage("IPMI", "Data berhasil di update !", ToastType.Success);
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    this.AddToastMessage("IPMI", "Data tidak berhasil di update !", ToastType.Error);
                    return Json(new { success = false }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {

                throw;
            }

            
        }

        // GET: Ipmi/Delete/5
        public ActionResult Delete(string id)
        {
            ViewBag.IdDept = GetDeptToList();
            object[] parameters = { id };
            ViewData["ListIpmi"] = objIpmi.GetbyID(parameters);
            return View();
        }

        // POST: Ipmi/Delete/5
        [HttpPost]
        public ActionResult Delete(tIpmi models)
        {
            int result = 0;

            object[] parameters = { models.NoIPMI};
            result = objIpmi.Delete(parameters);
            if (result == 1)
            {

                this.AddToastMessage("IPMI", "Data berhasil di hapus !", ToastType.Success);
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                this.AddToastMessage("IPMI", "Data tidak berhasil di hapus !", ToastType.Error);
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }
        #region VERIFIKASI
        public ActionResult Index3()
        {
            object[] nama = { User.Identity.Name };
            string NamaDept = objDept.GetDeptByID(nama);
            ViewBag.Dari = NamaDept;
            object[] dept = { NamaDept };
            var result = objIpmi.Get_IPMI_Verifikasi(dept);

            return View(result);
        }
        public ActionResult Verifikasi(string id)
        {
            ViewBag.IdDept = GetDeptToList();
            object[] parameters = { id };
            ViewData["ListIpmi"] = objIpmi.GetbyID(parameters);
            ViewData["ListAnalisa"] = ObjAnalisa.GetbyID(parameters);
            return View();
        }
        [HttpPost]
        public ActionResult Verifikasi(tIpmi models)
        {
            int result = 0;
            object[] parameters = { models.NoIPMI};
            result = objIpmi.Update_Status_Ipmi_Closed(parameters);
            if (result == 1)
            {

                this.AddToastMessage("IPMI", "Data berhasil di update !", ToastType.Success);
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                this.AddToastMessage("IPMI", "Data tidak berhasil di update !", ToastType.Error);
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult UnVerifikasi(tIpmi models, string FileName1)
        {
            int result = 0;
            object[] parameters = { models.NoIPMI, models.Ket, FileName1 };
            result = objIpmi.SetHistoryIpmi_UpdateStatus1(parameters);
            if (result == 1)
            {

                this.AddToastMessage("IPMI", "Data berhasil di update !", ToastType.Success);
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                this.AddToastMessage("IPMI", "Data tidak berhasil di update !", ToastType.Error);
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion
        #region CloseTask
        public ActionResult Index1()
        {
            object[] nama = { User.Identity.Name };
            string NamaDept = objDept.GetDeptByID(nama);
            ViewBag.Dari = NamaDept;
            object[] dept = { NamaDept };
            var result = objIpmi.GetIpmiClosed(dept);

            return View(result);
        }
        public ActionResult Details1(string id)
        {
            ViewBag.IdDept = GetDeptToList();
            object[] parameters = { id };
            ViewData["ListIpmi"] = objIpmi.GetbyID(parameters);
            return View();
        }

IPMI/Views/Ipmi/Create.cshtml
@model IPMI.Models.FileModels
@using IPMI.Models;
@{
    ViewBag.Title = "Identifikasi Masalah";
    var ListDept = ViewBag.IdDept;
    var AutoNo = ViewBag.AutoNO;
    List<StandartComboBox> ListCustomer = (List<StandartComboBox>)ViewData["Customer"];

}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                <div class="form-horizontal">
                    <h4>Create New</h4>
                    <hr />
                    <div class="form-group">
                        <input id="form_id" class="hidden" />
                        <label class="col-md-1 control-label" style="text-align:left;">NO IPMI</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input id="txtIpmi" class="form-control" disabled="disabled" value="@AutoNo" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Tanggal</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="text" class="form-control" id="txtDate">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Customer</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <select id="cmbCust" class="form-control select2" style="width: 100%;">
                                <option value="">Pilih Customer</option>
                                @foreach (var item in ListCustomer)
                                {
                                    <option value="@item.Value">@item.Text</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Dari</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="text" class="form-control" id="txtDept" value="@ViewBag.Dari" disabled="disabled">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Tujuan</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <select id="cmbDept" class="form-control select2" style="width: 100%;">
                                @foreach (var item in ListDept)
                                {
                                    <option value="@item.Value">@item.Text</option>
                                }
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left;">Problem</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <textarea class="form-control" rows="3" id="txtProblem" style="resize:none"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Jumlah</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="text" class="form-control" id="txtJml">
                        </div>
                    </div>
                    @*<section id="UploadForm">
                            @using (Html.BeginForm("UploadToDB", "Ipmi", FormMethod.Post, new { enctype = "multipart/form-data", id="MyForm" }))
                            {
                                <input type="file" name="postedFile" multiple="multiple" />
                                <input type="submit" id="btnUpload" value="Upload" />
                            }

                        </section>*@


                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">File</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="file" id="fileUpload" multiple="multiple">
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-5">
                            <button id="btnCreate" type="button" class="btn btn-primary" onclick="return Create()" style="width:100px"> Save</button>
                            <button id="btnBack" type="button" class="btn btn-primary" style="width:100px" onclick="location.href='@Url.Action("Index", "Ipmi")'"> Back To List</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>
        $(document).ready(function () {
            maxlength();
            $('#txtDate').datepicker({
                autoclose: true,
                orientation: "bottom left",
                todayHighlight: true
            });
            InitialConditions();
            $('.select2').select2()

            //$("#myForm").submit();
        })

        toastr.options = {
            "positionClass": "toast-bottom-right",
            "timeOut": "1000",
            "preventDuplicates": true
        }

        function UploadtoDB() {
            $.ajax({
                url: "/Ipmi/UploadToDB",
                type: "POST",
                data: function () {
                    var data = new FormData();
                    data.append("NoIpmi", jQuery("#txtIpmi").val());
                    data.append("postedFile", jQuery("#fileUpload").get(0).files[0]);
                    return data;
                }(),
                contentType: false,
                processData: false,
                success: function (response) {
                },
                error: function (jqXHR, textStatus, errorMessage) {
                    console.log(errorMessage);
                }
            });
        }

        function CreateUpload() {
            var txtIpmi1 = $("#txtIpmi").val();
            var data = new FormData();
            @*var saveUrl = '@Url.Action("UploadToDB", "Ipmi")';*@
            //var files = $("#fileUpload").get(0).files;
            //for (var i = 0; i < files.length; i++) {
            //    var newFileName = txtIpmi + "_" + files[i].name;
            //    data.append(files[i].name, files[i], txtIpmi + "_" + files[i].name);
            //}
            var files = $("#fileUpload").get(0).files;

            for (var i = 0; i < files.length; i++) {
                data.append("NoIpmi", txtIpmi1);
                data.append("New", true);
                data.append("postedFile", files[i]);
            }
            $.ajax({
                type: "POST",
                url: '@Url.Action("UploadToDB", "Ipmi")',
                processData: false,
                contentType: false,
                data: data
            });
            //var ajaxRequest = $.ajax({
            //    type: "POST",
            //    url: saveUrl,
            //    contentType: false,
            //    processData: false,
            //    data: data
            //});
            //ajaxRequest.done(function (xhr, textStatus) {
            //    alert('Done');
            //    // Do other operation

            //});

        }

        function InitialConditions() {

            $("#txtDate").val("");
            $("#txtProblem").val("");
            $("#txtJml").val("0");
        }
        function maxlength() {
            $('#txtProblem').keypress(function () {
                if (this.value.length >= 1000) // allowing you to enter only 10 chars.
                    return false;
            });
        }
        function Create() {
            var txtIpmi = $("#txtIpmi").val();
            //var cmbDept = $("#cmbDept option:selected").text();
            var txtDept = $("#txtDept").val();
            var txtDate = $("#txtDate").val();
            var cmbDept = $("#cmbDept option:selected").val();
            var cmbCust = $("#cmbCust option:selected").val();
            var cmbCust1 = $("#cmbCust option:selected").text();
            var txtProblem = $("#txtProblem").val();
            var txtJml = $("#txtJml").val();
            var IsExist = "0";
            var FileName = "";
            var fileInput = document.getElementById('fileUpload');

            if (fileInput != "" || fileInput != null) {
                var FileName = fileInput.value.split(/(\\|\/)/g).pop();
                if (FileName != "") {
                    IsExist = "1";
                    CreateUpload();
                }
            } else {
                IsExist = "0";
            }

            if (txtIpmi == "") {
                toastr.warning('No IPMI tidak boleh kosong')
                $("#txtIpmi").focus();
            }
            else if (cmbDept == "0") {
                toastr.warning('Pilih Department Tujuan')
                $("#cmbDept").focus();
            }
            else if (txtDate == "") {
                toastr.warning('Pilih Tanggal')
                $("#txtDate").focus();
            }
            else if (txtProblem == "") {
                toastr.warning('Problem canot be empty.')
                $("#txtProblem").focus();
            }
            else {
                //$("MyForm").submit();
                //$("#UploadForm").trigger("submit");
                var saveUrl = '@Url.Action("Create", "Ipmi")';
                var newUrl = '@Url.Action("Index", "Ipmi")';
                var models = {
                    NoIPMI: txtIpmi,
                    Tgl: txtDate,
                    CustomerId: cmbCust,
                    CustomerName: cmbCust1,
                    Dari: txtDept,
                    Masalah: txtProblem,
                    Jumlah: txtJml,
                    Ke: cmbDept,
                    FileName: IsExist,
                    FileName1: "0",
                };
                $.ajax({
                    type: "POST",
                    url: saveUrl,
                    data: models,
                    success: function (data) {
                        if (data.success) {
                            //alert('Succes')
                            //if (IsExist == "1") {
                            //    CreateUpload();
                            //}

                            window.location.href = newUrl;
                        } else {
                            //alert("Error");
                            window.location.href = saveUrl;
                        }
                    }
                });

            }
        }
    </script>
}

IPMI/Views/Ipmi/Delete.cshtml
@model IEnumerable<IPMI.Entity.tIpmi>
@using IPMI.Entity;
@{
    ViewBag.Title = "Identifikasi Masalah";
    var ListDept = ViewBag.IdDept;
    tIpmi tIpmi = (tIpmi)ViewData["ListIpmi"];

}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                <div class="form-horizontal">
                    <h4>Are you sure want to delete this?</h4>
                    <hr />
                    <div class="form-group">
                        <input id="form_id" class="hidden" />
                        <label class="col-md-1 control-label" style="text-align:left;">NO IPMI</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input id="txtIpmi" class="form-control" disabled="disabled" value="@tIpmi.NoIPMI" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Tanggal</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="text" class="form-control" id="txtDate" disabled="disabled" value="@tIpmi.Tgl">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Dari</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="text" class="form-control" id="txtDept" value="@tIpmi.Dari" disabled="disabled">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Tujuan</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <select id="cmbDept" class="form-control" disabled="disabled" required>
                                @foreach (var item in ListDept)
                                {
                                    <option value="@item.Value">@item.Text</option>
                                }
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left;">Problem</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <textarea class="form-control" rows="3" id="txtProblem" style="resize:none" disabled="disabled">@tIpmi.Masalah</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Jumlah</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="text" class="form-control" id="txtJml" value="@tIpmi.Jumlah" disabled="disabled">
                        </div>
                    </div>
                    <div class="form-group">
                        <label id="lblFile" class="col-md-1 control-label" style="text-align:left">File</label>
                        <label id="lblTick" class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="text" class="form-control" id="txtFile" value="@tIpmi.FileName" disabled="disabled">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-5">
                            <button id="btnCreate" type="button" class="btn btn-primary" onclick="return Delete()" style="width:100px"> Delete</button>
                            <button id="btnBack" type="button" class="btn btn-primary" style="width:100px" onclick="location.href='@Url.Action("Index", "Ipmi")'"> Back To List</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#txtDate').datepicker({
                autoclose: true,
                orientation: "bottom left",
                todayHighlight: true
            });
            //InitialConditions();
            $("#cmbDept").val("@tIpmi.ke");
        })
        toastr.options = {
            "positionClass": "toast-bottom-right",
            "timeOut": "1000",
            "preventDuplicates": true
        }
        function Delete() {
            var txtIpmi = $("#txtIpmi").val();
            if (txtIpmi == "") {
                toastr.warning('No data to delete.')
            }
            else {
                var saveUrl = '@Url.Action("Delete", "Ipmi")';
                var newUrl = '@Url.Action("Index", "Ipmi")';
                var models = {NoIPMI: txtIpmi};
                $.ajax({
                    type: "POST",
                    url: saveUrl,
                    data: {models},
                    success: function (data) {
                        if (data.success) {
                            window.location.href = newUrl;

                        } else {
                            window.location.href = newUrl;
                        }
                    }
                });
            }
        }
    </script>
}

IPMI/Views/Ipmi/Index.cshtml
@model IEnumerable<IPMI.Entity.tIpmi>
@using IPMI.Models;
@{

    ViewBag.Title = "Identifikasi Masalah - New Data";
    var no = 0;
    string dari = ViewBag.Dari;

}
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                @*<button class="btn btn-primary" onclick="return AddForm()"><span class="fa fa-plus"></span> Create New</button>*@
                @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary", @style = "width:100px" })
                <hr />
                <table id="table" class="table table-bordered table-striped _table" style="width:100%">
                    <thead>
                        <tr>
                            <th style="width:10px; text-align:center;">No</th>
                            <th style="width:60px; text-align:center;">Action</th>
                            <th>No IPMI</th>
                            <th>Tanggal</th>
                            <th>Dari</th>
                            <th>Ke</th>
                            <th style="width:150px; text-align:center;">Masalah</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody id="tbody">
                        @foreach (var item in Model)
                        {
                            no++;
                            <tr>
                                <td class="_i">@no</td>
                                <td style="text-align:center;">
                                    <button class="btn btn-xs btn-success" title="Edit" onclick="location.href='@Url.Action("Edit", "Ipmi")/@item.NoIPMI'"><span class="fa fa-pencil"></span></button>
                                    <button class="btn btn-xs btn-danger" title="Delete" onclick="location.href='@Url.Action("Delete", "Ipmi")/@item.NoIPMI'"><span class="fa fa-trash"></span></button>
                                    <button class="btn btn-xs btn-info" title="View" onclick="location.href='@Url.Action("Details", "Ipmi")/@item.NoIPMI'"><span class="fa fa-eye"></span></button>
                                    @if (item.FileName.ToString() != "0")
                                    {

                                        @*<button class="btn btn-xs btn-info" title="Download" onclick="location.href='@Url.Action("IndexDownload", "Analisa1")/@item.NoIPMI'"><span class="fa fa-arrow-down"></span></button>*@
                                        <button class="btn btn-xs btn-info" title="Download Identifikasi" onclick='window.location = "@Url.Action("IndexDownload", "Analisa1", new { NoIpmi = item.NoIPMI, Type=0 })";'><span class="fa fa-arrow-down"></span></button>
                                    }
                                </td>
                                <td class="_noipmi">@item.NoIPMI</td>
                                <td class="_tgl">@item.Tgl</td>
                                <td class="_dari">@item.Dari</td>
                                <td class="_ke">@item.ke</td>
                                <td class="_masalah">@item.Masalah</td>
                                <td class="_status">@item.Status</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        $(document).ready(function () {
            DataTable();

        })

        function DataTable() {
            $('#table').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                columnDefs: [{
                    targets: 3, render: function (data) {
                        return moment(data).format('DD-MM-YYYY');
                    }
                }]
            });
        }
        @*toastr.options = {
            "positionClass": "toast-bottom-right",
            "timeOut": "1000",
            "preventDuplicates": true
        }
        if ("@message" != "0") {
            toastr.success("Data Berhasil di simpan");
        }*@
    </script>
}