IPMI/Models/IM/IMDetailsModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IPMI.Models.IM
{
    public class IMDetailsModels
    {
        public int id { get; set; }
        public string NoIPMI { get; set; }
        public string Ke { get; set; }
    }
}

IPMI/Models/IM/IMModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IPMI.Models.IM
{
    public class IMModels
    {
        public int id { get; set; }
        [Key]
        public string NoIPMI { get; set; }
        public string Tgl { get; set; }
        public string Dari { get; set; }
        public string Ke { get; set; }
        public string NamaDept { get; set; }
        public string Masalah { get; set; }
        public int Jumlah { get; set; }
        public string Status { get; set; }
        public string FileName { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
       public DateTime CreatedDate { get; set; }
        public DateTime UpdateDate { get; set; }
    }
}

IPMI/Models/IM/IMRepos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IPMI.Models.IM
{
    public class IMRepos
    {
        public string AutoNo(String IdDept)
        {
            try
            {
                string sql =
                    @"DECLARE @Tahun varchar(4)
                            , @Bulan varchar(2) 
                            , @seq varchar(4)
                            , @ipmi char(4)
                    SET @ipmi ='IPMI'
                    SET @Tahun = datepart(year,getdate()) 
                    SET @Bulan = DATEPART(MONTH,getdate())
                    SET @dept = 'IT'
                    SET @seq = (SELECT RIGHT('0000'+ CAST(SUBSTRING(RTRIM(MAX(noipmi)),5,4) + 1 as Varchar),4) 
                                FROM tIpmi) 
                    SELECT @ipmi + '" + IdDept + "' + COALESCE(@seq, '0001') + @Bulan + @Tahun as AutoNo ";
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

IPMI/Controllers/IMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IPMI.Models.IM;
using IPMI.Models.Repo;
using IPMI.Master;
using System.IO;

namespace IPMI.Controllers
{

    public class IMController : Controller
    {
        [Authorize]
        // GET: Dept
        public ActionResult Index()
        {
            try
            {
                IMRepos repos = new IMRepos();
                ModelState.Clear();
                var result = repos.getListIM("");
                return View(result);
            }
            catch (Exception)
            {

                throw;
            }
        }

        // GET: /Dept/Edit/Create 
        //[Authorize(Roles = "Administrator, MIS")]
        public ActionResult Create()
        {
            IMModels iM = new IMModels();
            ModelState.Clear();
            ViewBag.IdDept = GetDeptToList();


            deptRepos deptrepos = new deptRepos();
            string Dept = deptrepos.getDeptByUser(User.Identity.Name);
            ViewBag.Dari = Dept;
            IMRepos repos = new IMRepos();
            string AutoNo = repos.AutoNo(Dept);
            ViewData["Dept"] = repos.GetDept();
            ViewBag.AutoNO = AutoNo;
            TempData["data"] = AutoNo;
            ViewData["ListDept"] = repos.GetDeptByUserLogin(User.Identity.Name);
            GetListIM();
            //GetListIMtDetail("0");
            //return View(iM);
            return View("Process");
        }

        public ActionResult GetListIM()
        {
            IMRepos repos = new IMRepos();
            ViewData["ListIM"] = repos.getListIM(User.Identity.Name);
            return PartialView("Partial/_GridProcess");
        }
        // POST: Dept
        //[Authorize(Roles = "Administrator, MIS")]
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(IMModels models)
        {
            try
            {
                IMRepos repo = new IMRepos();
                var CreatedBy = User.Identity.Name;
                var CreatedDate = DateTime.Now;
                var NoIpmi = models.NoIPMI.ToString();
                var Tgl = models.Tgl.ToString();
                var Dari = models.Dari.ToString();
                var Ke = models.Ke.ToString();
                var Masalah = models.Masalah.ToString();
                var Jumlah = models.Jumlah.ToString();
                var FileName = models.FileName.ToString();
                var ObjIM = new IMModels
                {
                    NoIPMI = NoIpmi,
                    Tgl = Tgl,
                    Dari = Dari,
                    Masalah = Masalah,
                    Jumlah = int.Parse(Jumlah),
                    FileName = FileName,
                    Ke = Ke,
                    CreatedBy = CreatedBy,
                    CreatedDate = CreatedDate
                    
                };

                
                repo.AddIM(ObjIM);

                deptRepos deptrepos = new deptRepos();
                string Dept = deptrepos.getDeptByUser(User.Identity.Name);
                ViewBag.Dari = Dept;
            }
            catch (Exception ex)
            {
                deptRepos deptrepos = new deptRepos();
                string Dept = deptrepos.getDeptByUser(User.Identity.Name);
                ViewBag.Dari = Dept;
                ModelState.AddModelError(string.Empty, ex.Message);
                //return View(iM);
            }
            return GetListIM();
        }
        // GET: /Dept/Edit/TestUser 
        //[Authorize(Roles = "Administrator, MIS")]
        public ActionResult Edit(string IdDept)
        {
            deptRepos repos = new deptRepos();

            try
            {
                if (IdDept == "")
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                var result = repos.getDeptByID(IdDept);
                if (result == null)
                    return HttpNotFound();
                return View(result.ToList());
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        //[Authorize(Roles = "Administrator, MIS")]
        public ActionResult Update(IMModels models)
        {
            try
            {
                IMRepos repo = new IMRepos();
                var UpdateBy = User.Identity.Name;
                var UpdateDate = DateTime.Now;
                var NoIpmi = models.NoIPMI.ToString();
                var Tgl = models.Tgl.ToString();
                var Dari = models.Dari.ToString();
                var Ke = models.Ke.ToString();
                var Masalah = models.Masalah.ToString();
                var Jumlah = models.Jumlah.ToString();
                var FileName = models.FileName.ToString();
                var ObjIM = new IMModels
                {
                    NoIPMI = NoIpmi,
                    Tgl = Tgl,
                    Dari = Dari,
                    Masalah = Masalah,
                    Jumlah = int.Parse(Jumlah),
                    FileName = FileName,
                    Ke = Ke,
                    UpdateDate = UpdateDate,
                    UpdatedBy = UpdateBy

                };
                repo.EditIM(ObjIM);
                
                deptRepos deptrepos = new deptRepos();
                string Dept = deptrepos.getDeptByUser(User.Identity.Name);
                ViewBag.Dari = Dept;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                throw;
            }
            return GetListIM();

        }

        [HttpPost]
        //[Authorize(Roles = "Administrator, MIS")]
        public ActionResult Delete(string IdDept)
        {
            if (IdDept == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                deptRepos repos = new deptRepos();
                repos.DeleteDeptById(IdDept);
                return Json(new { success = true, message = "Delete Successfully" }, JsonRequestBehavior.AllowGet);
                //return RedirectToAction("Index");
            }
        }

        private List<SelectListItem> GetDeptToList()
        {
            List<SelectListItem> SelectGroupListItems =
                new List<SelectListItem>();

            MasterRepository repos = new MasterRepository();
            var DeptSelectList = repos.GetDept();

            SelectGroupListItems.Add(
                new SelectListItem
                {
                    Text = "Select",
                    Value = "0"
                });

            foreach (var item in DeptSelectList)
            {
                SelectGroupListItems.Add(
                    new SelectListItem
                    {
                        Text = item.Text.ToString(),
                        Value = item.Value.ToString()
                    });
            }

            return SelectGroupListItems;
        }
        public ActionResult GetListIMtDetail(string Id)
        {
            IMRepos repos = new IMRepos();
            ViewData["ListIMDetail"] = repos.GetListRequestDetail(Id);
            return PartialView("Partial/_GridProcessDetail");
        }
        public ActionResult GetListIMtView(string Id)
        {
            IMRepos repos = new IMRepos();
            ViewData["ListIMDetail"] = repos.GetListRequestDetail(Id);
            return PartialView("Partial/_GridIMView");
        }
        public ActionResult Upload()
        {
            try
            {
                foreach (string upload in Request.Files)
                {
                    if (Request.Files[upload].FileName != "")
                    {
                        string path = AppDomain.CurrentDomain.BaseDirectory + "/App_Data/uploads/";
                        string filename = Path.GetFileName(Request.Files[upload].FileName);
                        Request.Files[upload].SaveAs(Path.Combine(path, filename));
                    }
                }
                return null;
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                throw;
            }
        }
    }
}

IPMI/Views/IM/Create.cshtml
@model IPMI.Models.IM.IMModels
@using IPMI.Models
@{
    List<StandartComboBox> Dept = (List<StandartComboBox>)ViewData["Dept"];
    ViewBag.Title = "IDENTIFIKASI MASALAH";
}

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                @Html.AntiForgeryToken()
                <div class="box-body">
                    <div class="form-horizontal">
                        <h4>Create IM</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <label class="col-md-1 control-label" style="text-align:left;">No IPMI</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                @Html.Editor("AutoNO", new { htmlAttributes = new { @class = "form-control", @id = "form_no", disabled = "disabled", @readonly = "readonly" } })
                                @*@Html.ValidationMessageFor(model => model.NoIPMI, "", new { @class = "text-danger" })*@
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-1 control-label" style="text-align:left;">Tanggal</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                @Html.EditorFor(model => model.Tgl, new { htmlAttributes = new { @class = "form-control", @id = "form_tgl" } })
                                @Html.ValidationMessageFor(model => model.Tgl, "", new { @class = "text-danger" })
                                @*@Html.TextBoxFor(m => m.Tgl, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "datetime-local" })
                                    @Html.ValidationMessageFor(m => m.Tgl, "", new { @class = "text-danger" })*@
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-1 control-label" style="text-align:left;">Dari</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <select id="form_process_name" class="form-control">
                                    @foreach (var item in Dept)
                                    {
                                        <option value="@item.Value">@item.Text</option>
                                    }
                                </select>
                                @*@Html.DropDownList("IdDept", null, new { @class = "form-control", @id = "form_IdDept" })*@
                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-md-1 control-label" style="text-align:left;">Problem</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <textarea class="form-control" rows="3" id="problem" style="resize:none"></textarea>
                                @*@Html.TextAreaFor(model => model.Masalah, new { style = "width: 435px; height:50px;" })*@
                                @*@Html.TextAreaFor(model => model.Masalah, new { htmlAttributes = new { @class = "form-control", @id = "form_M" }, @cols = 68, @rows = 4 })*@
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-1 control-label" style="text-align:left;">Jumlah</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-2">
                                @Html.EditorFor(model => model.Jumlah, new { htmlAttributes = new { @class = "form-control", @id = "form_J" } })
                                @Html.ValidationMessageFor(model => model.Jumlah, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <hr />
                        <div id="tabledetail">
                            @Html.Partial("Partial/_GridIMdetails")
                        </div>
                    </div>
                </div>

            </div>
            <div class="box-footer">
                <div class="col-sm-offset-4 col-md-offset-5 col-sm-8 col-md-7">
                    <button class="btn btn-primary" onclick="return Save()"><span class="fa fa-save"></span> Save</button>
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="AddPopUp" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content  panel panel-primary">
                <div class="panel-heading">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h2 class="modal-title">Add New Detail</h2>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-3 col-md-4 control-label text-muted" style="text-align:left;">Department Tujuan</label>
                            <label class="col-sm-1 col-md-1 control-label text-muted ">:</label>
                            <div class="col-sm-8 col-md-7">
                                <input id="add_description" class="form-control" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" onclick="return AddDetail()"><span class="bold fa fa-plus">&nbsp;&nbsp;Add</span></button>&nbsp;
                    <button type="button" class="btn btn-default" data-dismiss="modal"><span class="bold fa fa-times">&nbsp;&nbsp;Cancel</span></button>
                </div>
            </div>
        </div>
    </div>


    @*@section Scripts {
            <script>
                function Save() {
                    var IdDept = model => model.IdDept;
                    var NamaDept = model => model.NamaDept;
                    var url = "@Url.Action("Create","IM")";
                    var model = {
                        IdDept: IdDept,
                        NamaDept: NamaDept
                    };
                    $.post(url, model);
                }

            </script>
        }*@
}

IPMI/Views/IM/Index.cshtml
@model IEnumerable<IPMI.Models.IM.IMModels>
@{
    ViewBag.Title = "LIST IM";
    var no = 0;
}
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                <a href="@Url.Action("Create","IM")" class="btn btn-primary"><span class="fa fa-plus"></span> Add New</a>
                <hr />
                <table id="table" class="table table-bordered table-striped table-condensed">
                    <thead style="color:#357CA5">
                        <tr>
                            <a href="~/Views/IM/Index.cshtml">~/Views/IM/Index.cshtml</a>
                            <th style="width:10px; text-align:center;">No</th>
                            <th>No IPMI</th>
                            <th>Tanggal</th>
                            <th>Dari</th>
                            <th>Masalah</th>
                            <th>Jumlah</th>
                            <th>Status</th>
                            <th style="width:40px; text-align:center;">Action</th>
                        </tr>
                    </thead>
                    <tbody id="tbody">
                        @foreach (var item in Model)
                        {
                            no++;
                        <tr>
                            <td class="_i">@no</td>
                            <td class="_NoIPMI">@item.NoIPMI</td>
                            <td>@item.Tgl</td>
                            <td>@item.Dari</td>
                            <td>@item.Masalah</td>
                            <td>@item.Jumlah</td>
                            <td>@item.Status</td>
                            <td style="text-align:center;">
                                @Html.ActionLink(" ", "Edit", new { IdDept = item.NoIPMI }, new { @class = "btn btn-xs btn-success fa fa-pencil" })
                                <button class="btn btn-xs btn-danger" type="button" title="Delete Parameter" onclick="Delete($(this))"><span class="fa fa-trash"></span></button>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function ()
        {
            DataTable();
        })

        function DataTable()
        {
            $('#table').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth":false
            });
        }

        function Delete(data) {
            var saveUrl = '@Url.Action("Delete", "Dept")';
            var newUrl = '@Url.Action("Index", "Dept")';
            var IdDept = data.closest("tr").find("._IdDept").text();
            //alert(id);
            if (confirm("Delete Data ?")) {
                $.ajax({
                    type: "POST",
                    url: saveUrl,
                    data: { IdDept: IdDept},
                    success: function (data) {
                        if (data.success) {
                            //DataTable.ajax.reload();


                            //alert(data.message);
                            window.location.href = newUrl;
                            //$.notify(data.message, {
                            //    globalPosition: "top center",
                            //    className: "success"
                            //})
                        }
                    }
                });
            }
        }
    </script>
}