IPMI/Controllers/Analisa1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IPMI.Entity;
using IPMI.Repository;
using IPMI.Services;
using IPMI.Models;
using IPMI.Models.Repo;
using System.IO;
using System.IO.Compression;
using System.Configuration;
using System.Data.SqlClient;
using ICSharpCode.SharpZipLib.Zip;
using System.Net.Mail;
using System.Net;
using System.Text;
using System.Data;

namespace IPMI.Controllers
{
    public class Analisa1Controller : Controller
    {
        private IMService objIpmi;
        private DeptService objDept;
        private AnalisaService ObjAnalisa;
        public Analisa1Controller()
        {
            this.objIpmi = new IMService();
            this.objDept = new DeptService();
            this.ObjAnalisa = new AnalisaService();
        }
        // GET: Analisa1
        public ActionResult Index()
        {
            object[] nama = { User.Identity.Name };
            string NamaDept = objDept.GetDeptByID(nama);
            ViewBag.Dari = NamaDept;
            object[] dept = { NamaDept };
            var result = ObjAnalisa.GetAll(dept);
            return View(result);
        }

        // GET: Analisa1/Details/5
        public ActionResult Details(string id, string state)
        {
            ViewBag.state = state;
            object[] parameters = { id };
            ViewData["ListAnalisa"] = ObjAnalisa.GetbyID(parameters);
            return View();
        }

        // GET: Analisa1/Create
        public ActionResult Create(string id)
        {
            ViewBag.NoIpmi = id;
            return View();
        }

        // POST: Analisa1/Create
        [HttpPost]
        public ActionResult Create(tIpmiAnalisa models)
        {
            int result = 0;
            int result1 = 0;
            models.CreatedBy = User.Identity.Name;
            object[] parameters = { models.NoIPMI, models.Penyebab
                                        ,models.RencanaPerbaikan, models.Target
                                        ,models.PIC, models.TglActual
                                        ,models.CreatedBy};
            result = ObjAnalisa.Insert(parameters);
            
            if (result == 1)
            {
                object[] param = { models.NoIPMI };
                result1 = objIpmi.UpdateStatusIpmi(param);
                if (result1 == 1)
                {                
                    
                    this.AddToastMessage("IPMI", "Data berhasil di simpan !", ToastType.Success);
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    this.AddToastMessage("IPMI", "update status Ipmi failed !", ToastType.Error);
                    return Json(new { success = false }, JsonRequestBehavior.AllowGet);
                }
                
            }
            else
            {
                this.AddToastMessage("IPMI", "Data Tidak Berhasil di simpan !", ToastType.Error);
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Analisa1/Edit/5
        public ActionResult Edit(string id)
        {
            object[] parameters = { id };
            ViewData["ListAnalisa"] = ObjAnalisa.GetbyID(parameters);
            return View();
            //string query = (ViewData["ListAnalisa"] ?? string.Empty) as string;
            //if (string.IsNullOrEmpty(query))
            //{
            //    this.AddToastMessage("IPMI", "Silahkan Edit dulu data di tab buat baru !", ToastType.Warning);
            //    return null;
            //}
            //else
            //{
            //    return View();
            //}            
        }

        // POST: Analisa1/Edit/5
        [HttpPost]
        public ActionResult Edit(tIpmiAnalisa models, bool IsExist)
        {
            int result = 0;
            int result1 = 0;
            models.UpdatedBy = User.Identity.Name;
            object[] parameters = { models.NoIPMI, models.Penyebab
                                        ,models.RencanaPerbaikan, models.Target
                                        ,models.PIC, models.TglActual
                                        ,models.CreatedBy};
            result = ObjAnalisa.Update(parameters);
            if (result == 1)
            {
                object[] param = { models.NoIPMI,models.TglActual };
                result1 = ObjAnalisa.UpdateStatusIpmi(param);
                if (result1 == 1)
                {
                    if (IsExist)
                    {
                        ObjAnalisa.UpdateFileAnalisa(models.NoIPMI);
                    }

                    string Dari = string.Empty;
                    string Masalah = string.Empty;
                    string Ke = string.Empty;
                    DataTable dt = new DataTable();
                    dt = objIpmi.GetIpmiByNo(models.NoIPMI);
                    if (dt.Rows.Count > 0)
                    {
                        Dari = dt.Rows[0][0].ToString();
                        Masalah = dt.Rows[0][2].ToString();
                        Ke = dt.Rows[0][1].ToString();

                        string email = string.Empty;
                        email = objIpmi.GetEmailAnalisa(Dari);

                        //MailMessage mail = new MailMessage("ipmi@tsmu.co.id", email);
                        MailMessage mail = new MailMessage();
                        mail.IsBodyHtml = true;
                        mail.From = new MailAddress("ipmi@tsmu.co.id", "IPMI");
                        mail.To.Add(new MailAddress(email));
                        var smpt = new SmtpClient
                        {
                            Host = "mail.tsmu.co.id",
                            Port = 25,
                            EnableSsl = false,
                            DeliveryMethod = SmtpDeliveryMethod.Network,
                            Credentials = new NetworkCredential("ipmi@tsmu.co.id", "svPyyO(++6cj"),
                            Timeout = 20000
                        };
                        var body = new StringBuilder();
                        body.AppendFormat("Analisa dan Perbaikan masalah :");
                        body.AppendLine(@"<br />>Dari =" + Ke);
                        body.AppendLine(@"<br />>Masalah =" + Masalah);
                        body.AppendLine(@"<br />>Penyebab =" + models.Penyebab);
                        body.AppendLine(@"<br />>Rencana Perbaikan =" + models.RencanaPerbaikan);
                        body.AppendLine("<br /><a href='https://srv02.tsmu.co.id/ipmi/Account/Login?ReturnUrl=%2Fipmi%2F'>Klik di sini untuk Login</a>");
                        mail.Body = body.ToString();
                        string emailSubject = "IPMI Notification " + models.NoIPMI;
                        mail.Subject = emailSubject;
                        //mail.Body = @"Masalah sudah di analisa : <br /> > Dari =" + models.Dari + "<br /> > Msalah = " + models.Masalah + "<br /> <a href='https://srv02.tsmu.co.id/ipmi/Account/Login?ReturnUrl=%2Fipmi%2F'>Klik di sini untuk Login</a>";
                        mail.IsBodyHtml = true;
                        mail.CC.Add("log@tsmu.co.id");
                        smpt.Send(mail);
                    }
                  
                    this.AddToastMessage("IPMI", "Data berhasil di update !", ToastType.Success);
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    this.AddToastMessage("IPMI", "update status Ipmi failed !", ToastType.Error);
                    return Json(new { success = false }, JsonRequestBehavior.AllowGet);
                }
                
            }
            else
            {
                this.AddToastMessage("IPMI", "Data tidak berhasil di update !", ToastType.Error);
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Analisa1/Delete/5
        public ActionResult Delete(string id)
        {
            object[] parameters = { id };
            ObjAnalisa = new AnalisaService();
            ViewData["ListAnalisa"] = ObjAnalisa.GetbyID(parameters);
            return View();
        }

        // POST: Analisa1/Delete/5
        [HttpPost]
        public ActionResult Delete(tIpmiAnalisa models)
        {
            int result = 0;
            int result1 = 0;
            object[] parameters = { models.NoIPMI };
            result = ObjAnalisa.Delete(parameters);
            if (result == 1)
            {
                object[] param = { models.NoIPMI };
                result1 = objIpmi.UpdateStatusIpmi_Open(param);
                if (result1 == 1)
                {
                    this.AddToastMessage("IPMI", "Data berhasil di hapus !", ToastType.Success);
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    this.AddToastMessage("IPMI", "Data tidak berhasil di hapus !", ToastType.Error);
                    return Json(new { success = false }, JsonRequestBehavior.AllowGet);
                }
               
            }
            else
            {
                this.AddToastMessage("IPMI", "Data tidak berhasil di hapus !", ToastType.Error);
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }
      
        public ActionResult Download(string FileName)
        {
            FileDownloads obj = new FileDownloads();
            //////int CurrentFileID = Convert.ToInt32(FileID);  
            var filesCol = obj.GetFile(FileName).ToList();
            using (var memoryStream = new MemoryStream())
            {

IPMI/Views/Analisa1/Create.cshtml
@using IPMI.Entity
@using IPMI.Models
@model tIpmi
@{
    ViewBag.Title = "Create";
    var NoIpmi = ViewBag.NoIpmi;
}

<div id="CreateForm">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <h3 id="title_form"></h3>
                    <hr />
                    <div class="form-horizontal">
                        <div class="form-group">
                            <input id="form_id" class="hidden" />
                            <label class="col-md-2 control-label" style="text-align:left;">NO IPMI</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <input id="txtIpmi" class="form-control" disabled="disabled" value="@NoIpmi" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label" style="text-align:left">Penyebab</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <textarea class="form-control" rows="2" id="txtPenyebab" style="resize:none"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label" style="text-align:left;">R. Perbaikan</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <input type="text" input id="txtPerbaikan" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label" style="text-align:left">Target</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <input type="text" class="form-control" id="txtTarget">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label" style="text-align:left">PIC</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <input type="text" class="form-control" id="txtPIC">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label" style="text-align:left">Tgl Aktual</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <input type="text" class="form-control" id="txtTgl">
                            </div>
                        </div>
                      
                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-5">
                                <button class="btn btn-primary" onclick="return SaveAnalisa()"><span class="fa fa-save"></span> Save</button>
                                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @*<div class="box-footer">
                    <div class="col-md-offset-2 col-md-5">
                        <button id="btnCreate" type="button" class="btn btn-primary" onclick="return Create()"><span class="bold fa fa-floppy-o">&nbsp;&nbsp;Save</span></button>&nbsp;
                        <button id="btnUpdate" type="button" class="btn btn-primary" onclick="return Edit()"><span class="bold fa fa-save">&nbsp;&nbsp;Update</span></button>&nbsp;
                        <button type="button" id="btnBack" class="btn btn-primary" onclick=""><span class="bold fa fa-angle-left">&nbsp;&nbsp;Back To List</span></button>
                    </div>
                </div>*@
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('#txtTgl').datepicker({
                autoclose: true,
                orientation: "top left",
                todayHighlight: true
            });
            $('#txtTarget').datepicker({
                autoclose: true,
                orientation: "bottom left",
                todayHighlight: true
            });
            InitialConditions();
        })

        toastr.options = {
            "positionClass": "toast-bottom-right",
            "timeOut": "5000",
            "preventDuplicates": true
        }
        function InitialConditions() {
            $("#txtPenyebab").val("");
            $("#txtPerbaikan").val("");
            $("#txtTarget").val("");
            $("#txtPIC").val("");
            $("#txtPenyebab").focus();
        }        

        function SaveAnalisa() {
            var saveUrl = '@Url.Action("Create","Analisa1")';
            var newUrl = '@Url.Action("Index","Analisa1")';

            var NoIpmi = $("#txtIpmi").val();
            var Penyebab = $("#txtPenyebab").val();
            var Perbaikan = $("#txtPerbaikan").val();
            var Target = $("#txtTarget").val();
            var PIC = $("#txtPIC").val();
            var Tgl = $("#txtTgl").val();            

            if (Penyebab == "") {
                toastr.warning('Penyebab empty !')
                $("#txtPenyebab").focus();
            } else if (Perbaikan == "") {
                toastr.warning('Rencana Perbaikan empty !')
                $("#txtPerbaikan").focus();
            } else if (Target == "") {
                toastr.warning('Target empty !')
                $("#txtTarget").focus();
            } else if (PIC == "") {
                toastr.warning('PIC empty !')
                $("#txtPIC").focus();
            } else {
                var models = {
                    NoIPMI: NoIpmi,
                    Penyebab: Penyebab,
                    RencanaPerbaikan: Perbaikan,
                    Target: Target,
                    PIC: PIC,
                    TglActual: Tgl
                };
                $.ajax({
                    type: "POST",
                    url: saveUrl,
                    data: {models},
                    success: function (data) {
                        if (data.success)
                            window.location.href = newUrl;
                            //toastr.success(data.message)
                    }
                });
                @*var url = '@Url.Action("Create","Analisa")';
                var model = {
                    NoIpmi: NoIpmi,
                    Penyebab: Penyebab,
                    RPerbaikan: Perbaikan,
                    Target: Target,
                    PIC: PIC,
                    Tgl: Tgl
                };
                $.post(url, model);*@
            }

        }
    </script>
}

IPMI/Views/Analisa1/Delete.cshtml
@model IEnumerable<IPMI.Entity.tIpmiAnalisa>
@using IPMI.Entity;
@{
    ViewBag.Title = "Analisa & Perbaikan Masalah - OnProgress";
    tIpmiAnalisa analisa = (tIpmiAnalisa)ViewData["ListAnalisa"];

}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                <div class="form-horizontal">
                    <h4>Are you sure want to delete this?</h4>
                    <hr />
                    <div class="form-group">
                        <input id="form_id" class="hidden" />
                        <label class="col-md-1 control-label" style="text-align:left;">NO IPMI</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input id="txtIpmi" class="form-control" disabled="disabled" value="@analisa.NoIPMI" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Penyebab</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <textarea class="form-control" rows="2" id="txtPenyebab" style="resize:none" disabled="disabled">@analisa.Penyebab</textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left;">R. Perbaikan</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="text" input id="txtPerbaikan" class="form-control" value="@analisa.RencanaPerbaikan" disabled="disabled" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Target</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="text" class="form-control" id="txtTarget" value="@analisa.Target" disabled="disabled">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">PIC</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="text" class="form-control" id="txtPIC" value="@analisa.PIC" disabled="disabled">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" style="text-align:left">Tgl Aktual</label>
                        <label class="col-md-1 control-label">:</label>
                        <div class="col-md-5">
                            <input type="text" class="form-control" id="txtTgl" value="@analisa.TglActual" disabled="disabled">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-5">
                            <button id="btnCreate" type="button" class="btn btn-primary" onclick="return Delete()" style="width:100px"> Delete</button>
                            <button id="btnBack" type="button" class="btn btn-primary" style="width:100px" onclick="location.href='@Url.Action("Index1", "Analisa1")'"> Back To List</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#txtDate').datepicker({
                autoclose: true,
                orientation: "bottom left",
                todayHighlight: true
            });
            //InitialConditions();
        })
        toastr.options = {
            "positionClass": "toast-bottom-right",
            "timeOut": "1000",
            "preventDuplicates": true
        }
        function Delete() {
            var txtIpmi = $("#txtIpmi").val();
            if (txtIpmi == "") {
                toastr.warning('No data to delete.')
            }
            else {
                var saveUrl = '@Url.Action("Delete", "Analisa1")';
                var newUrl = '@Url.Action("Index1", "Analisa1")';
                var models = { NoIpmi: txtIpmi};
                $.ajax({
                    type: "POST",
                    url: saveUrl,
                    data: {models},
                    success: function (data) {
                        if (data.success) {
                            window.location.href = newUrl;

                        } else {
                            window.location.href = newUrl;
                        }
                    }
                });
            }
        }
    </script>
}

IPMI/Views/Analisa1/Details.cshtml
@model IEnumerable<IPMI.Entity.tIpmi>
@using IPMI.Entity;
@{
    ViewBag.Title = "Analisa & Perbaikan Masalah - OnProgress";
    tIpmiAnalisa analisa = (tIpmiAnalisa)ViewData["ListAnalisa"];
}

<div id="CreateForm">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-horizontal">
                        <h4>Details</h4>
                        <hr />
                        <div class="form-group">
                            <input id="form_id" class="hidden" />
                            <label class="col-md-1 control-label" style="text-align:left;">NO IPMI</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <input id="txtIpmi" class="form-control" disabled="disabled" value="@analisa.NoIPMI" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-1 control-label" style="text-align:left">Penyebab</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <textarea class="form-control" rows="2" id="txtPenyebab" style="resize:none" disabled="disabled">@analisa.Penyebab</textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-1 control-label" style="text-align:left;">R. Perbaikan</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <input type="text" input id="txtPerbaikan" class="form-control" value="@analisa.RencanaPerbaikan" disabled="disabled" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-1 control-label" style="text-align:left">Target</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <input type="text" class="form-control" id="txtTarget" value="@analisa.Target" disabled="disabled">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-1 control-label" style="text-align:left">PIC</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <input type="text" class="form-control" id="txtPIC" value="@analisa.PIC" disabled="disabled">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-1 control-label" style="text-align:left">Tgl Aktual</label>
                            <label class="col-md-1 control-label">:</label>
                            <div class="col-md-5">
                                <input type="text" class="form-control" id="txtTgl" value="@analisa.TglActual" disabled="disabled">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-5">
                                @if (@ViewBag.state == "2")
                                {
                                    <button id="btnBack" type="button" class="btn btn-primary" style="width:100px" onclick="location.href='@Url.Action("Index2", "Analisa1")'"> Back To List</button>
                                }
                                else if (@ViewBag.state == "1")
                                {
                                    <button id="btnBack" type="button" class="btn btn-primary" style="width:100px" onclick="location.href='@Url.Action("Index1", "Analisa1")'"> Back To List</button>
                                }
                                else
                                {
                                    <button id="btnBack" type="button" class="btn btn-primary" style="width:100px" onclick="location.href='@Url.Action("Index3", "Analisa1")'"> Back To List</button>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

IPMI/Views/Analisa1/Index2.cshtml
@model IEnumerable<IPMI.Entity.tIpmi>
@using IPMI.Models;
@{

    ViewBag.Title = "Analisa & Perbaikan Masalah - Closed";
    var no = 0;

}
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                <hr />
                <table id="table" class="table table-bordered table-striped _table" style="width:100%">
                    <thead>
                        <tr>
                            <th style="width:10px; text-align:center;">No</th>
                            <th style="width:60px; text-align:center;">Action</th>
                            <th>No IPMI</th>
                            <th>Tanggal</th>
                            <th>Dari</th>
                            <th>Masalah</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody id="tbody">
                        @foreach (var item in Model)
                        {
                            no++;
                            <tr>
                                <td class="_i">@no</td>
                                <td style="text-align:center;">
                                    @*<button class="btn btn-xs btn-info" title="View" onclick="location.href='@Url.Action("Details", "Analisa1")/@item.NoIPMI/2'"><span class="fa fa-eye"></span></button>*@
                                    <button class="btn btn-xs btn-info" title="View" onclick="ViewDetails('@item.NoIPMI', '2')"><span class="fa fa-eye"></span></button>
                                </td>
                                <td class="_noipmi">@item.NoIPMI</td>
                                <td class="_tgl">@item.Tgl</td>
                                <td class="_dari">@item.Dari</td>
                                <td class="_masalah">@item.Masalah</td>
                                <td class="_status">@item.Status1</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        $(document).ready(function () {
            DataTable();
        })

        function DataTable() {
            $('#table').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                columnDefs: [{
                    targets: 3, render: function (data) {
                        return moment(data).format('L');
                    }
                }]
            });
        }
        @*toastr.options = {
            "positionClass": "toast-bottom-right",
            "timeOut": "1000",
            "preventDuplicates": true
        }
        if ("@message" != "0") {
            toastr.success("Data Berhasil di simpan");
        }*@

        function ViewDetails(NoIpmi, state) {

            var url = '@Url.Action("Details", "Analisa1")';
            url += '?id=' + NoIpmi + '&state=' + state;
            window.location.href = url;
        }
    </script>
}

IPMI/Views/Analisa1/IndexDownload.cshtml
@{
    ViewBag.Title = "Download";
    var NoIpmi = ViewBag.NoIpmi;
    var Type = ViewBag.Type;
}

@using (Html.BeginForm("DownloadMultipleFiles1", "Analisa1", new { NoIpmi= NoIpmi, Type= Type }, FormMethod.Post, null))
{
        <input type="submit" value="Download" />
}