IPMI/Controllers/DeptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IPMI.Models;
using IPMI.Models.Master;
using IPMI.Models.Repo;

namespace IPMI.Controllers
{
    public class DeptController : Controller
    {
        // GET: Dept
        public ActionResult Index()
        {
            try
            {
                deptRepos dept = new deptRepos();
                ModelState.Clear();
                var result = dept.getListDepts();
                return View(result);
            }
            catch (Exception)
            {

                throw;
            }
        }

        // GET: /Dept/Edit/Create 
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            
            deptModels dept = new deptModels();
            ModelState.Clear();

            return View(dept);
        }

        // POST: Dept
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(deptModels dept)
        {
            try
            {
                deptRepos repo = new deptRepos();
                if (dept == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var IdDept = dept.IdDept.Trim().ToUpper();
                var NamaDept = dept.NamaDept.Trim().ToUpper();

                if (IdDept == null || IdDept == "") throw new Exception("ID Dept empty !");

                if (NamaDept == "") throw new Exception("Nama Department empty !");

                bool isValid = repo.isDeptExist(IdDept);
                if (isValid)
                {
                    throw new Exception("Data Exist !");
                }
                
                var ObjDept = new deptModels { IdDept = IdDept, NamaDept = NamaDept };
                
                repo.AddDept(ObjDept);
                this.AddToastMessage("", "Data saved", ToastType.Success);
                return Redirect("~/Dept/Index");

            }
            catch (Exception ex)
            {
                this.AddToastMessage("Error", ex.Message, ToastType.Error);
                //ModelState.AddModelError(string.Empty, ex.Message);
                return View(dept);
            }
        }
        // GET: /Dept/Edit/TestUser 
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(string IdDept)
        {
            deptRepos repos = new deptRepos();

            try
            {
                if (IdDept == "")
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                var result = repos.getDeptByID(IdDept);
                if(result == null)
                    return HttpNotFound();
                return View(result.ToList());
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public ActionResult Update(deptModels dept)
        {
            if (dept.IdDept == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                deptRepos repos = new deptRepos();
                repos.EditDept(dept);
                return Json(new { success = true, message = "Update Successfully" }, JsonRequestBehavior.AllowGet);
                //return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Delete(string IdDept)
        {
            try
            {
                if (IdDept == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {
                    deptRepos repos = new deptRepos();
                    bool IsExist = repos.IsDataExist(IdDept);
                    if (IsExist)
                    {
                        throw new Exception("Data already declare in User Table, cannot be deleted !");
                       
                    }
                    repos.DeleteDeptById(IdDept);
                    this.AddToastMessage("IPMI", "Delete Successfully", ToastType.Success);
                    return Json(new { success = true, message = "Delete Successfully" }, JsonRequestBehavior.AllowGet);
                    //return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                //this.AddToastMessage("IPMI", ex.Message, ToastType.Warning);
                return Json(new { success = false, message = ex.Message}, JsonRequestBehavior.AllowGet);
                throw;
            }
            
        }
    }
}

IPMI/Controllers/ReportsController.cs
using IPMI.Models.Repo;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IPMI.Models;
using IPMI.Entity;
using IPMI.Services;
using IPMI.Repository;
namespace IPMI.Controllers
{
    public class ReportsController : Controller
    {
        private DeptService objDept;

        public ReportsController()
        {
            this.objDept = new DeptService();
        }
        // GET: Reports
        public ActionResult Index()
        {
            deptRepos dept = new deptRepos();
            ModelState.Clear();
            var result = dept.getListDepts();
            return View(result);
        }
        public ActionResult Index1()
        {

            List<ReportModels> models = new List<ReportModels>() {
                new ReportModels(){FieldName = "Dari (Departemen)", Type = 1},
                new ReportModels(){FieldName = "Ke (Departemen)", Type = 2},
                new ReportModels(){FieldName = "Tanggal", Type = 3}
            };
            
            
            return View(models);
        }
        public ActionResult IndexAnalisa()
        {
            deptRepos dept = new deptRepos();
            ModelState.Clear();
            var result = dept.getListDepts();
            return View(result);
        }
        [HttpPost]
        public ActionResult ShowLaporanIpmiByDept(string id)
        {

            ReportIMrepo report = new ReportIMrepo();
            this.HttpContext.Session["ReportNameIM"] = "ReportIM.rpt";
            this.HttpContext.Session["ReportIM"] = report.LaporanIPMIbyDept(id);
            this.HttpContext.Session["ReportIMDetails"] = report.LaporanIPMIDetails("");

            return Json(new { result = true }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult ShowLaporanAnalisaIpmiByDept(string id)
        {

            ReportIMrepo report = new ReportIMrepo();
            this.HttpContext.Session["ReportNameIManalisa"] = "ReportIManalisa.rpt";
            this.HttpContext.Session["ReportIManalisa"] = report.LaporanIPMIbyDept(id);
            this.HttpContext.Session["ReportIManalisaSub"] = report.LaporanIPMIanalisa();

            return Json(new { result = true }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetParameter1(string FieldName)
        {

            var result = GetDeptToList();
            return new JsonResult { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public ActionResult ShowLaporanAIPMI_New(string Dari, string Ke, string From, string To )
        {


            if (From.Replace(@";", string.Empty) == "" || From == null)
            {
                From = "ALL";
            }
            if (To.Replace(@";", string.Empty) == "" || To == null)
            {
                To = "ALL";
            }
            ReportIMrepo report = new ReportIMrepo();
            this.HttpContext.Session["ReportNameIM"] = "ReportIM_1.rpt";
            this.HttpContext.Session["ReportIM"] = report.LaporanIPMI_1(Dari, Ke, From, To);
            //this.HttpContext.Session["ReportIMDetails"] = report.LaporanIPMIanalisa_Subreport();

            return Json(new { result = true }, JsonRequestBehavior.AllowGet);
        }
        private List<SelectListItem> GetDeptToList()
        {
            List<SelectListItem> SelectGroupListItems =
                new List<SelectListItem>();

            List<StandartComboBox> standartCombos = new List<StandartComboBox>();
            var dept = objDept.GetAll();
            foreach (var item in dept)
            {
                standartCombos.Add(
                    new StandartComboBox
                    {
                        Value = item.IdDept,
                        Text = item.NamaDept
                    });
            }

            SelectGroupListItems.Add(
                new SelectListItem
                {
                    Text = "ALL DEPARTEMEN",
                    Value = "ALL"
                });

            foreach (var item in standartCombos)
            {
                SelectGroupListItems.Add(
                    new SelectListItem
                    {
                        Text = item.Text.ToString(),
                        Value = item.Value.ToString()
                    });
            }

            return SelectGroupListItems;
        }
    }

}

IPMI/Views/Reports/Index.cshtml
@model IEnumerable<IPMI.Models.Master.deptModels>
@{
    ViewBag.Title = "REPORT IDENTIFIKASI MASALAH";
    var no = 0;
}
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                @*<button class="btn btn-xs btn-danger" type="button" title="Print All Report" onclick="PrintAll()"><span class="fa fa-bar-chart-o"></span></button>*@
                <button type="button" title="Print All Report" class="btn btn-primary" onclick="return PrintAll()"><span class="bold fa fa-bar-chart-o">&nbsp;&nbsp;Print All</span></button>&nbsp;
                <hr />
                <table id="table" class="table table-bordered table-striped table-condensed">
                    <thead style="color:#357CA5">
                        <tr>
                            <th style="width:10px; text-align:center;">No</th>
                            <th style="width:50px;">ID Dept</th>
                            <th>Nama Department</th>
                            <th style="width:40px; text-align:center;">Action</th>
                        </tr>
                    </thead>
                    <tbody id="tbody">
                        @foreach (var item in Model)
                        {
                            no++;
                            <tr>
                                <td class="_i">@no</td>
                                <td class="_IdDept">@item.IdDept</td>
                                <td>@item.NamaDept</td>
                                <td style="text-align:center;">
                                    <button class="btn btn-xs btn-danger" type="button" title="Print Report" onclick="ViewReport($(this))"><span class="fa fa-bar-chart-o"></span></button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function ()
        {
            DataTable();
        })
        toastr.options = {
            "positionClass": "toast-bottom-right",
            "timeOut": "5000",
            "preventDuplicates": true
        }
        function DataTable()
        {
            $('#table').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth":false
            });
        }

        function Delete(data) {
            var saveUrl = '@Url.Action("Delete", "Dept")';
            var newUrl = '@Url.Action("Index", "Dept")';
            var IdDept = data.closest("tr").find("._IdDept").text();
            //alert(id);
            if (confirm("Delete Data ?")) {
                $.ajax({
                    type: "POST",
                    url: saveUrl,
                    data: { IdDept: IdDept},
                    success: function (data) {
                        if (data.success) {
                            //DataTable.ajax.reload();
                            alert(data.message);
                            window.location.reload();
                            //toastr.success('Delete Successfully.')
                            //alert(data.message);
                            //window.location.href = newUrl;
                            //$.notify(data.message, {
                            //    globalPosition: "top center",
                            //    className: "success"
                            //})
                        } else {
                            alert(data.message);
                        }
                    }
                });
            }
        }

        function ViewReport(data) {
            var IdDept = data.closest("tr").find("._IdDept").text();

            $.ajax({
                type: "POST",
                url: '@Url.Action("ShowLaporanIpmiByDept", "Reports")',
                data: {id: IdDept},
                success: function (data) {
                    if (!data.result) {
                        alert("Error");
                    }
                    else {
                        window.open("../Report/rptIM.aspx", '_blank');
                    }
                }
            });
        }

        function PrintAll() {
            var IdDept = 'ALL';

            $.ajax({
                type: "POST",
                url: '@Url.Action("ShowLaporanIpmiByDept", "Reports")',
                data: {id: IdDept},
                success: function (data) {
                    if (!data.result) {
                        alert("Error");
                    }
                    else {
                        window.open("../Report/rptIM.aspx", '_blank');
                    }
                }
            });
        }
    </script>
}

IPMI/Views/Reports/IndexAnalisa.cshtml
@model IEnumerable<IPMI.Models.Master.deptModels>
@{
    ViewBag.Title = "REPORT ANALISA & PERBAIKAN MASALAH";
    var no = 0;
}
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                @*<button class="btn btn-xs btn-danger" type="button" title="Print All Report" onclick="PrintAll()"><span class="fa fa-bar-chart-o"></span></button>*@
                <button type="button" title="Print All Report" class="btn btn-primary" onclick="return PrintAll()"><span class="bold fa fa-bar-chart-o">&nbsp;&nbsp;Print All</span></button>&nbsp;
                <hr />
                <table id="table" class="table table-bordered table-striped table-condensed">
                    <thead style="color:#357CA5">
                        <tr>
                            <th style="width:10px; text-align:center;">No</th>
                            <th style="width:50px;">ID Dept</th>
                            <th>Nama Department</th>
                            <th style="width:40px; text-align:center;">Action</th>
                        </tr>
                    </thead>
                    <tbody id="tbody">
                        @foreach (var item in Model)
                        {
                            no++;
                            <tr>
                                <td class="_i">@no</td>
                                <td class="_IdDept">@item.IdDept</td>
                                <td>@item.NamaDept</td>
                                <td style="text-align:center;">
                                    <button class="btn btn-xs btn-danger" type="button" title="Print Report" onclick="ViewReport($(this))"><span class="fa fa-bar-chart-o"></span></button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function ()
        {
            DataTable();
        })
        toastr.options = {
            "positionClass": "toast-bottom-right",
            "timeOut": "5000",
            "preventDuplicates": true
        }
        function DataTable()
        {
            $('#table').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth":false
            });
        }

      
        function ViewReport(data) {
            var IdDept = data.closest("tr").find("._IdDept").text();

            $.ajax({
                type: "POST",
                url: '@Url.Action("ShowLaporanAnalisaIpmiByDept", "Reports")',
                data: {id: IdDept},
                success: function (data) {
                    if (!data.result) {
                        alert("Error");
                    }
                    else {
                        window.open("../Report/rptIMAnalisa.aspx", '_blank');
                    }
                }
            });
        }

        function PrintAll() {
            var IdDept = 'ALL';

            $.ajax({
                type: "POST",
                url: '@Url.Action("ShowLaporanAnalisaIpmiByDept", "Reports")',
                data: {id: IdDept},
                success: function (data) {
                    if (!data.result) {
                        alert("Error");
                    }
                    else {
                        window.open("../Report/rptIMAnalisa.aspx", '_blank');
                    }
                }
            });
        }
    </script>
}